# Generated by Django 3.1.2 on 2020-10-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(max_length=50)),
                ('warranty', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='toshiba_photo/')),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='lg_ar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(max_length=50)),
                ('warranty', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='toshiba_photo/')),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
